name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: justgook/setup-elm@1.2.0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
